# -*- coding: utf-8 -*-
#
# This file is part of HEPData.
# Copyright (C) 2020 CERN.
#
# HEPData is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# HEPData is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with HEPData; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

dist: xenial

addons:
  postgresql: "9.6"

notifications:
  email: false

sudo: false

language: python

cache:
  - pip

services:
  - postgresql
  - redis
  - xvfb

python:
  - "3.6"

before_install:
  # See: https://docs.travis-ci.com/user/database-setup/#Installing-specific-versions-of-ElasticSearch
  # Also: https://stackoverflow.com/questions/55951531/running-elasticsearch-7-0-on-a-travis-xenial-build-host
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.1.1-amd64.deb
  - sudo dpkg -i --force-confnew elasticsearch-7.1.1-amd64.deb
  - sudo sed -i.old 's/-Xms1g/-Xms256m/' /etc/elasticsearch/jvm.options
  - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo systemctl start elasticsearch
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "travis_retry psql -c \"CREATE USER hepdata WITH CREATEDB PASSWORD 'hepdata';\" -U postgres"
  - "travis_retry psql -c 'CREATE DATABASE hepdata_test OWNER hepdata;' -U postgres"

install:
  - "travis_retry pip install --force-reinstall -r requirements.txt"
  - "travis_retry pip install -e .[all,postgresql]"
  - "travis_retry hepdata db init"
  - "travis_retry hepdata db create"
  - "travis_retry hepdata utils reindex -rc True"
  - "travis_retry npm update && npm install --silent -g node-sass clean-css@3.4.28 uglify-js requirejs"
  - "hepdata npm"
  - "cd /home/travis/virtualenv/python3.6.7/var/hepdata-instance/static/"
  - "travis_retry npm install"
  - "hepdata collect -v"
  - "hepdata assets build"
  - "cd /home/travis/build/HEPData/hepdata"

before_script:
  - "/home/travis/build/HEPData/hepdata/scripts/sc_tunnel_start.sh"
  - "cp /home/travis/build/HEPData/hepdata/hepdata/config_local.travis.py /home/travis/build/HEPData/hepdata/hepdata/config_local.py"

script:
  # Secure environment variables are not available for forked repositories, so omit end-to-end tests run on Sauce Labs.
  - "if [[ -z ${SAUCE_USERNAME} || -z ${SAUCE_ACCESS_KEY} ]]; then py.test tests -k 'not tests/e2e'; else py.test tests; fi"
  - "rm /home/travis/build/HEPData/hepdata/hepdata/{config_local.py,__pycache__/config_local*}"

after_success:
  - "coveralls"

after_script:
  - "/home/travis/build/HEPData/hepdata/scripts/sc_tunnel_stop.sh"

deploy:
  - provider: script
    skip_cleanup: true
    script: cd $TRAVIS_BUILD_DIR; ./build-and-deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: cd $TRAVIS_BUILD_DIR; ./build-and-deploy.sh
    on:
      tags: true
