# -*- coding: utf-8 -*-
#
# This file is part of HEPData.
# Copyright (C) 2015 CERN.
#
# HEPData is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# HEPData is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with HEPData; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

addons:
  postgresql: "9.6"

notifications:
  email: false

sudo: false

language: python

cache:
  - pip

services:
  - postgresql
  - elasticsearch
  - redis-server

python:
  - "2.7"

before_install:
  # See: https://docs.travis-ci.com/user/database-setup/#Installing-specific-versions-of-ElasticSearch
  - "curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.1.1/elasticsearch-2.1.1.deb && sudo dpkg -i --force-confnew elasticsearch-2.1.1.deb && sudo service elasticsearch restart"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder
  - travis_retry psql -c "CREATE USER hepdata WITH CREATEDB PASSWORD 'hepdata';" -U postgres
  - "travis_retry psql -c 'CREATE DATABASE hepdata_test OWNER hepdata;' -U postgres"

install:
  - "travis_retry pip install -r requirements.txt"
  - "travis_retry pip install -e .[all,postgresql] --pre"
  - "travis_retry hepdata db init"
  - "travis_retry hepdata db create"
  - "travis_retry hepdata utils reindex -rc True"
  - "travis_retry npm update && npm install --silent -g node-sass@3.8.0 clean-css@3.4.24 uglify-js requirejs"
  - "hepdata npm"
  - "cd /home/travis/virtualenv/python2.7.14/var/hepdata-instance/static/"
  - "travis_retry npm install"
  - "hepdata collect -v"
  - "hepdata assets build"
  - "cd /home/travis/build/HEPData/hepdata"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3" # give xvfb some time to start

script:
  - "py.test tests -k 'not tests/e2e'"

after_success:
  - coveralls
